name: Deploy Static HTML

on:
  workflow_dispatch:  # This allows the manual trigger
    inputs:
      deploy_branch:
        description: 'Select the branch to deploy'
        required: true
        default: 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        run: echo "Add your build steps here, if necessary"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./index.html  # Adjust the path to your HTML files
          publish_branch: gh-pages  # Assuming you are using GitHub Pages
